Η http://www.oracle.com/us/technologies/java/index.html[Java] είναι μία 
γλώσσα προγραμματισμού υψηλού επιπέδου.

Μεταγλώτιση και Εκτέλεση (compilers and execution)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Για να τρέξουμε προγράμματα γραμμένα σε Java χρειαζόμαστε το http://www.java.com/en/download/manual.jsp[Java Runtime 
Enviroment (JRE)].

Για να μεταγλωττίσουμε προγράμματα γραμμένα σε Java
χρειάζόμαστε το http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java Development Kit (JDK)].

Και για τα 2 παραπάνω μπορούμε να χρησιμοποιήσουμε το http://openjdk.java.net/[OpenJDK]
που διατίθεται υπό http://openjdk.java.net/legal/gplv2+ce.html[GPLv2 with Classpath Exception].

Συγγραφή Προγραμμάτων
~~~~~~~~~~~~~~~~~~~~~

Μπορούμε να γράψουμε προγράμματα σε Java εύκολα με τον αγαπημένο μας 
editor όπως π.χ. το gedit ή geany ή vim.

Αφού γράψουμε το κώδικα Java τα εργαλεία του OpenJDK μας επιτρέπουν να 
μεταγλωττίσουμε και να τρέξουμε τα προγραμματά μας. Η διαδικασία είναι
η εξής:

[source,bash]
javac myprogram.java #Μεταγλώττιση του κώδικα myprogram.java
java myprogram       #Εκτέλεση του κώδικα myprogram.class

Προφανώς οι παραπάνω εντολές εξαρτώνται από τη δομή του κωδικά σας.

Περιβάλλοντα Εργασίας - IDE
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Για αυτούς που θέλουν να χρησιμοποιήσουν κάποιο IDE υπάρχουν αρκετά
αξιόλογα για τη Java. Εμείς θα σας προτείνουμε το http://netbeans.org/[NetBeans].

Το NetBeans περιέχει πάρα πολλά εργαλεία ενσωματωμένα που στοχεύουν να
διευκολύνουν το προγραμματιστή και να αυξήσουν την αποδοτικότητά του.

Μερικά από τα http://netbeans.org/features/index.html[χαρακτηριστικά του NetBeans] 
είναι αυτόματη συμπλήρωση κώδικα, άμεση διόρθωση λαθών, refactoring κ.α.

Το NetBeans διατίθεται υπό http://netbeans.org/about/legal/license.html[CDDL και GPLv2 with Classpath Exception].

Μία άλλη εναλλακτική επιλογή είναι το http://www.eclipse.org/[Eclipse] που
διατίθεται υπό την http://www.eclipse.org/legal/epl-v10.html[Eclipse Public License - v 1.0].

