Βασικά στοιχεία
^^^^^^^^^^^^^^^

Η C είναι μια διαδικαστική γλώσσα προγραμματισμού γενικής χρήσης. Χαρακτηρίζεται
για τη ταχύτητα της, καθώς και το γεγονός ότι είναι διαθέσιμη στα περισσότερα
σημερινά λειτουργικά συστήματα. Η C είναι μια γλώσσα υψηλού επιπέδου, αν και
θεωρείται από πολλούς mid-level γλώσσα προγραμματισμού και συχνά αποκαλείται
"high-level assembly" (υψηλού επιπέδου συμβολική γλώσσα).

Κατά την ανάπτυξή της, έχουν γίνει προσπάθειες
http://www.open-std.org/JTC1/SC22/WG14/www/standards[τυποποίησής] της, με τo
πρότυπο ANSI (http://c-faq.com/ansi/index.html[ANSI C] και αργότερα
http://www.open-std.org/jtc1/sc22/wg14/[ISO C]). Η τελευταία του έκδοση είναι το
C99. Πoλλοί compilers ακόμα δεν υποστηρίζουν πλήρως (ή πλήρως σωστά) πολλά
χαρακτηριστικά που περιγράφονται στο πρότυπο αυτό. Για το λόγο αυτό συνήθως
ζητείται συμβατότητα με το πρότυπο C89/C90. Υπό-κατασκευή βρίσκεται και το
νεότερο πρότυπο C1X.

Τα βασικά εργαλεία που χρειαζόμαστε για να εργαστούμε με την C σε μια διανομή
Linux είναι τα παρακάτω:

 * Επεξεργαστής κειμένου
 * Compiler για τη μετάφραση του κώδικα

Ως επεξεργαστή κειμένου μπορούμε να χρησιμοποιήσουμε οποιονδήποτε προτιμάμε, πχ
vim, nano, gedit, κλπ. Για κονσόλα επίσης κάνει οποιαδήποτε, πχ gnome-terminal,
kterm, xterm, κλπ.

Μεταγλώττιση και Εκτέλεση (compilers and execution)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Για τη μετάφραση και μεταγλώττιση του κώδικά μας θα χρειαστούμε κάποιον
compiler. Ο πιο ευρέως γνωστός είναι ο http://gcc.gnu.org/[GCC] (μέρος
του http://www.gnu.org/[GNU project]).

Συγγραφή Προγραμμάτων
^^^^^^^^^^^^^^^^^^^^^

[source,c]
---------------------------------------------------------------------
#include <stdio.h>

int main(void) {
    printf("Hello, World!\n");
    return 0;
}
---------------------------------------------------------------------

Αφού γράψουμε το κώδικα μας, αποθηκεύουμε το αρχείο με κατάληξη *.c*. Για να
μεταγλωττίσουμε το κώδικα μας τρέχουμε σε ένα τερματικό:

[source,shell]
$ gcc -o hello hello.c      # μετάφραση και μεταγλώττιση του κώδικα.
                            # παράγει το εκτελέσιμο αρχείο "hello"
$ ./hello                   # εκτέλεση του αρχείου
> Hello, World!

