Βασικά στοιχεία
^^^^^^^^^^^^^^^

Η http://pascal-central.com/ppl/index.html[Pascal] είναι μία δομημένη γλώσσα
προγραμματισμού με ιδιαίτερο χαρακτηριστικό τη δυνατότητα ορισμού από τον
προγραμματιστή δικών του δομών δεδομένων.

Τα βασικά εργαλεία που χρειαζόμαστε για να εργαστούμε με την Pascal σε μια διανομή
Linux είναι τα παρακάτω:

 * Επεξεργαστής κειμένου (editor)
 * Compiler
 * Debugger
 * Κονσόλα (terminal) για την εκτέλεση των προγραμμάτων που δημιουργούμε

Ως επεξεργαστή κειμένου μπορούμε να χρησιμοποιήσουμε οποιονδήποτε προτιμάμε, πχ
vim, nano, gedit, κλπ. Για κονσόλα επίσης κάνει οποιαδήποτε, πχ gnome-terminal,
kterm, xterm, κλπ.

Μεταγλώτιση και Εκτέλεση (compilers and execution)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Για τη μεταγλώτιση θα χρησιμοποιήσουμε τον http://www.gnu-pascal.de/gpc/[GNU
Pascal Compiler] ή αλλιώς gpc. Η γενική χρήση του gpc είναι η εξής:

[source,shell]
$ gpc [options] file

[source,pascal]
program HelloWorld(output);
begin
    writeln('Hello, World!')
end

Έστω ότι έχουμε δημιουργήσει το αρχείο με κώδικα Pascal που έχει όνομα hello.pas
. Για να το μεταγλωττίσουμε εκτελούμε:

[source,shell]
$ gpc hello.pas

Η παραπάνω εντολή, αν δεν υπάρχουν λάθη στον κώδικα του hello.pas, θα
δημιουργήσει ένα εκτελέσιμο αρχείο με όνομα a.out . Αν θέλουμε να ορίσουμε εμείς
το όνομα του εκτελέσιμου αρχείου θα πρέπει να χρησιμοποιήσουμε τον διακόπτη -o
ακολουθούμενο από το επιθυμητό όνομα. Επίσης, χρήσιμος διακόπτης είναι ο -Wall ο
οποίος ορίζει ότι θέλουμε να εμφανίζονται όλα τα μηνύματα του gpc κατά τη
μεταγλώτιση, όπως προειδοποιήσεις (warnings). Οπότε, μία πιο σωστή χρήση του gpc
στο παράδειγμά μας θα ήταν:

[source,shell]
$ gpc -Wall -o hello hello.pas
$ ./hello
> Hello, World!

Αποσφαλμάτωση (debugging)
^^^^^^^^^^^^^^^^^^^^^^^^^

Για την αποσφαλμάτωση των προγραμμάτων μας προτείνουμε τον GNU Debugger ή αλλιώς
τον gdb. Για να τον χρησιμοποιήσουμε, η μεταγλώτιση του προγράμματός μας θα
πρέπει να γίνει με τη χρήση του διακόπτη -g, δηλαδή:

[source,shell]
$ gpc -g -Wall -o hello hello.pas

Στη συνέχεια, εκτελούμε τον gdb δίνοντας ως όρισμα το εκτελέσιμο που
δημιουργήσαμε με την παραπάνω εντολή:

[source,shell]
$ gdb hello

Η χρήση του gdb ξεφεύγει από το σκοπό του παρόντος κειμένου, καθώς αποτελεί
μέρος της διδακτέας ύλης του μαθήματος. Το πλήρες manual του gdb είναι διαθέσιμο
http://www.gnu.org/software/gdb/documentation/[εδώ].

