Βασικά στοιχεία
^^^^^^^^^^^^^^^

Η C++ είναι μια γλώσσα προγραμματισμού γενικής χρήσης.Είναι μια γλώσσα υψηλού 
επιπέδου, αν και θεωρείται από πολλούς μέσου επιπέδου (mid-level) γλώσσα 
προγραμματισμού καθώς συνδυάζει στοιχεία από γλώσσες υψηλού και χαμηλού
επιπέδου.

Η γλώσσα αναπτύχθηκε ως βελτίωση της ήδη υπάρχουσας γλώσσας προγραμματισμού
C, και αρχικά ονομάστηκε _C with Classes_ (C με κλάσεις).


Η γλώσσα ορίστηκε παγκοσμίως, το 1998, με το πρότυπο ISO/IEC 14882:1998. 
Το πρότυπο τροποποιήθηκε το 2003 από το τεχνικό επιμελητήριο, ISO/IEC 14882:2003. 
Η τρέχουσα έκδοση αυτού του προτύπου είναι αυτή του Σεπτεμβρίου του 2011, 
η ISO/IEC 14882:2011 (άτυπα γνωστή και ως C++11).

Τα βασικά εργαλεία που χρειαζόμαστε για να εργαστούμε με την C σε μια διανομή
Linux είναι τα παρακάτω:

 * Επεξεργαστής κειμένου
 * Compiler για τη μετάφραση του κώδικα

Ως επεξεργαστή κειμένου μπορούμε να χρησιμοποιήσουμε οποιονδήποτε προτιμάμε, πχ
vim, nano, gedit, κλπ. Για κονσόλα επίσης κάνει οποιαδήποτε, πχ gnome-terminal,
kterm, xterm, κλπ.

Μεταγλώτιση και Εκτέλεση (compilers and execution)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Για τη μετάφραση και μεταγλώττιση του κώδικά μας θα χρειαστούμε κάποιον
compiler. Ο πιο ευρέως γνωστος είναι ο http://gcc.gnu.org/[GCC] (μέρος
του http://www.gnu.org/[GNU project]).

Συγγραφή Προγραμμάτων
^^^^^^^^^^^^^^^^^^^^^

[source,c]
---------------------------------------------------------------------
#include <iostream>
 
int main()
{
   std::cout << "Hello, world!";
}
---------------------------------------------------------------------

Αφού γράψουμε το κώδικα μας, αποθηκεύουμε το αρχείο με κατάληξη *.c*. Για να
μεταγλωττίσουμε το κώδικα μας τρέχουμε σε ένα τερματικό:

[source,shell]
$ g++ -o hello hello.c      # μετάφραση και μεταγλώττιση του κώδικα.
                            # παράγει το εκτελέσιμο αρχείο "hello"
$ ./hello                   # εκτέλεση του αρχείου
> Hello, World!

Περιβάλλοντα Εργασίας - IDE
^^^^^^^^^^^^^^^^^^^^^^^^^^^

Για αυτούς που θέλουν να χρησιμοποιήσουν κάποιο IDE υπάρχουν αρκετά
αξιόλογα για τη C++. Μερικά γνωστά είναι το http://www.codeblocks.org/[Code::Blocks],
το http://www.codelite.org/[Codelite] και το http://www.bloodshed.net/dev/[Bloodshed Dev-C + +].

[[Dev-cpp]]
Bloodshed Dev-C++
+++++++++++++++++

Το περιβάλλον εργασίας Bloodshed Dev-C++ είναι απλό στη χρήση και προσφέρει
αρκετές λειτουργίες όπως αυτόματη συμπλήρωση, υποστήριξη CVS, λειτουργία
αποσφαλμάτωσης κλπ.

Το Bloodshed Dev-C++ διανέμεται υπό την άδεια GPLv3 και διατίθεται μόνο
για Windows.
