Η MySQL είναι ενα σύστημα διαχείρισης σχεσιακών βάσεων δεδομένων που μετρά
περισσότερες από 11 εκατομμύρια εγκαταστάσεις. Έλαβε το όνομά της από την κόρη
του Μόντυ Βιντένιους, τη My. Το πρόγραμμα τρέχει έναν εξυπηρετητή (server)
παρέχοντας πρόσβαση πολλών χρηστών σε ένα σύνολο βάσεων δεδομένων.

Ο κώδικας του εγχειρήματος είναι διαθέσιμος μέσω της GNU General Public License,
καθώς και μέσω ορισμένων ιδιόκτητων συμφωνιών. Ανήκει και χρηματοδοτείται από
μία και μοναδική κερδοσκοπική εταιρία, τη σουηδική MySQL AB, η οποία σήμερα
ανήκει στην Oracle. Mερικές γνωστές εφαρμογές που αξιοποιούν την Mysql είναι: το
TYPO3, το Joomla, το Wordpress, η MyBB, η phpBB, το Drupal καθώς και ως μέρος
της υποδομής των Wikipedia, Google, filckr, Nokia.com, Youtube, Facebook και
Twitter.

Χρησιμοποιείται συνήθως ως κεντρικό συστατικό του πακέτου λογισμικού LAMP
(ακρώνυμο για το Linux, Apache, MySQL, Perl/PHP/Python. Είναι γραμμένη σε `C`
και `C++` ενώ υπάρχει πληθώρα βιβλιοθηκών που επιτρέπει την χρήση της MySQL σε
προγράμματα άλλων γλωσσών.

Χρήση
^^^^^

Αφού εγκατασταθεί η MySQL μέσω του package manager της διανομής του χρήστη,
είτε ξεχωριστά είτε ως μέρος του πακέτου λογισμικού LAMP, πρέπει να εκκινηθεί
ο MySQL server για να μπορέσει να χρησιμοποιηθεί.

Σε Debian διανομές και παράγωγες του (π.χ. Ubuntu) ο server ξεκινάει με

[source,shell]
# /etc/init.d/mysql start

Αφού ξεκινήσει ο MySQL server συνδέεστε σε αυτόν απο κονσόλα με

[source,shell]
# mysql -u root

και αν συνδέεστε για πρώτη φορά πιθανότατα θα σας ζητήσει να δώσετε ενα
νέο password για τον root χρήστη. Οι υπόλοιπες ρυθμίσεις για την MySQL
βρίσκονται συνήθως στο `/etc/mysql/my.cnf` .

Υπάρχουν επίσης διαθέσιμα και εργαλεία με γραφικό περιβάλλον για την διαχείριση
της βάσης δεδομένων. Μερικά απο τα πιο γνωστά είναι τα _MySQL Workbench_,
_phpMyAdmin_ και _HeidiSQL_.
