Το http://www.scilab.org/[Scilab] είναι μία εφαρμογή αριθμητικών υπολογισμών,
αλλά και μία υψηλού επιπέδου γλώσσα προγραμματισμού προσανατολισμένη σε
αριθμητικούς υπολογισμούς.

Μπορεί να χρησιμοποιηθεί για ανάλυση σήματος, στατιστική ανάλυση, ανάλυση
εικόνας, προσομοιώσεις ρευστοδυναμικής κλπ.

Ο κώδικας του *Matlab* μοιάζει σε συντακτικό και μπορεί να μετατραπεί σε
αυτόν του Scilab.

Το Scilab διανέμεται υπό την http://www.cecill.info/licences/Licence_CeCILL_V2-en.html[CeCILL] άδεια
που είναι συμβατή με τη GPL.

Συγγραφή Προγραμμάτων
^^^^^^^^^^^^^^^^^^^^^

Εκτελέστε το Scilab, και χρησιμοποιείστε τον επεξεργαστή κειμένου για να
δημιουργήσετε ένα αρχείο πηγαίου κώδικα που μοιάζει με αυτό:

[source,scilab]
----
//
//  Print a fixed message to the screen.
//
function hello

  mprintf('Hello, world \n');

endfunction
----

Αφού γράψουμε το κώδικα μας, τον αποθηκεύουμε με κατάληξη *.sci*. Έπειτα μέσα
από το διερμηνέα εντολών του Scilab τρέχουμε:

[source,scilab]
--> getf hello.sci  // το φορτώνουμε στη μνήμη
--> hello           // το εκτελούμε

Εναλλακτικές
^^^^^^^^^^^^

Παρόμοια λειτουργικότητα παρέχουν και τα πακέτα λογισμικού http://www.sagemath.org/[Sage]
και http://www.gnu.org/software/octave/license.html[Octave] που
διατίθενται υπό την άδεια GPL.
