Βασικά στοιχεία
^^^^^^^^^^^^^^^

Η `C++` είναι μια γλώσσα προγραμματισμού γενικής χρήσης, υψηλού
επιπέδου, αν και θεωρείται από πολλούς μέσου επιπέδου (mid-level) 
καθώς συνδυάζει στοιχεία από γλώσσες υψηλού και χαμηλού επιπέδου.

Η γλώσσα αναπτύχθηκε ως βελτίωση της ήδη υπάρχουσας γλώσσας προγραμματισμού
C, και αρχικά ονομάστηκε _C with Classes_ (C με κλάσεις).

Η γλώσσα ορίστηκε παγκοσμίως, το 1998, με το πρότυπο ISO/IEC 14882:1998.
Το πρότυπο τροποποιήθηκε το 2003 από το τεχνικό επιμελητήριο, ISO/IEC 14882:2003.
Η τρέχουσα έκδοση αυτού του προτύπου είναι αυτή του Σεπτεμβρίου του 2011,
η ISO/IEC 14882:2011 (άτυπα γνωστή και ως `C++11`).

Τα βασικά εργαλεία που χρειαζόμαστε για να εργαστούμε με την C σε μια διανομή
Linux είναι τα παρακάτω:

 * Επεξεργαστής κειμένου
 * Compiler για τη μετάφραση του κώδικα

Ως επεξεργαστή κειμένου μπορούμε να χρησιμοποιήσουμε οποιονδήποτε προτιμάμε, πχ
vim, nano, gedit, κλπ. Για κονσόλα επίσης κάνει οποιαδήποτε, πχ gnome-terminal,
kterm, xterm, κλπ.

Μεταγλώττιση και Εκτέλεση (compilers and execution)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Για τη μετάφραση και μεταγλώττιση του κώδικά μας θα χρειαστούμε κάποιον
compiler. Ο πιο ευρέως γνωστός είναι ο http://gcc.gnu.org/[GCC] (μέρος
του http://www.gnu.org/[GNU project]).

Συγγραφή Προγραμμάτων
^^^^^^^^^^^^^^^^^^^^^

[source,cpp]
---------------------------------------------------------------------
#include <iostream>

using namespace std;

int main()
{
    cout << "Hello, world!";
    return 0;
}
---------------------------------------------------------------------

Αφού γράψουμε το κώδικα μας, αποθηκεύουμε το αρχείο με κατάληξη *.cpp*. Για να
μεταγλωττίσουμε το κώδικα μας τρέχουμε σε ένα τερματικό:

[source,shell]
 $ g++ -o hello hello.cpp     # μετάφραση και μεταγλώττιση του κώδικα.
                              # παράγει το εκτελέσιμο αρχείο "hello"
 $ ./hello                    # εκτέλεση του αρχείου
 > Hello, World!

Περιβάλλοντα Εργασίας - IDE
^^^^^^^^^^^^^^^^^^^^^^^^^^^

Για αυτούς που θέλουν να χρησιμοποιήσουν κάποιο IDE υπάρχουν αρκετά
αξιόλογα για τη `C++`. Μερικά γνωστά είναι το http://www.codeblocks.org/[Code::Blocks],
το http://www.codelite.org/[Codelite] και το http://www.bloodshed.net/dev/[Bloodshed `Dev-C++`].

[[Dev-cpp]]
Bloodshed `Dev-C++`
+++++++++++++++++++

Το περιβάλλον εργασίας Bloodshed `Dev-C++` είναι απλό στη χρήση και προσφέρει
αρκετές λειτουργίες όπως αυτόματη συμπλήρωση, υποστήριξη CVS, λειτουργία
αποσφαλμάτωσης κλπ.

Το Bloodshed `Dev-C++` διανέμεται υπό την άδεια GPLv3 και διατίθεται μόνο
για Windows.

[[CodeBlocks]]
Code::Blocks
++++++++++++

Μία άλλη πολύ καλή επιλογή είναι το Codeblocks. Το Codeblocks περιλαμβάνει
μία πληθώρα χαρακτηριστικών που συνεισφέρουν στη γρήγορη, εύκολη και αποδοτική
συγγραφή κώδικα. Υποστηρίζει πληθώρα διαφορετικών μεταγλωττιστών και κάνει
χρήση του GNU GDB για αποσφαλμάτωση του κώδικα.

To Codeblocks είναι γραμμένο σε `C++` και είναι επεκτάσιμο μέσω plugins.
Λειτουργεί σε Linux, Mac και Windows και διανέμεται υπό την άδεια GPLv3.
