Βασικά στοιχεία
^^^^^^^^^^^^^^^

Η FORTRAN (FORmulae TRANslator) είναι μία από τις πρώτες γλώσσες προγραμματισμού
υψηλού επιπέδου. Αρχικά η FORTRAN προοριζόταν για επίλυση μαθηματικών
προβλημάτων και χρησιμοποιήθηκε σε επιστημονικές αλλά και εμπορικές εφαρμογές.

Το όνομα της FORTRAN γράφεται παραδοσιακά με κεφαλαία από τότε που η χρήση
πεζών γραμμάτων για την αναπαράσταση λέξεων κλειδιών δεν χρησιμοποιούταν.
Πλέον επίσημα αναφερόμαστε τη γλώσσα ως Fortran (από τη Fortran 90 και μετά).
Αυτή η σύμβαση αντικατοπτρίζεται στην αναφορά με κεφαλαία της FORTRAN στα ANSI X3.9-1966 
(FORTRAN 66) και ANSI X3.9-1978 (FORTRAN 77) πρότυπα και έπειτα ως
Fortran στα ANSI X3.198-1992 (Fortran 90), ISO/IEC 1539-1:1997 (Fortran 95)
και ISO/IEC 1539-1:2004 (Fortran 2003) πρότυπα.

Τα βασικά εργαλεία που χρειαζόμαστε για να εργαστούμε με την Fortran σε μια διανομή
Linux είναι τα παρακάτω:

 * Επεξεργαστής κειμένου
 * Compiler για τη μετάφραση του κώδικα

Ως επεξεργαστή κειμένου μπορούμε να χρησιμοποιήσουμε οποιονδήποτε προτιμάμε, πχ
vim, nano, gedit, κλπ. Για κονσόλα επίσης κάνει οποιαδήποτε, πχ gnome-terminal,
kterm, xterm, κλπ.

Mεταγλώττιση και Εκτέλεση (compilers and execution)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Για τη μετάφραση και μεταγλώττιση του κώδικά μας θα χρειαστούμε κάποιον
compiler. Θα χρησιμοποιήσουμε το http://gcc.gnu.org/wiki/GFortran[GFortran] (μέρος
του http://www.gnu.org/[GNU project]).

Συγγραφή Προγραμμάτων
^^^^^^^^^^^^^^^^^^^^^

[source,fortran]
---------------------------------------------------------------------
program hello
    print *, "Hello, World!"
end program hello
---------------------------------------------------------------------

Αφού γράψουμε το κώδικα μας, αποθηκεύουμε το αρχείο με κατάληξη *.f* (ή
*.FOR*, *.for*, *.f77*, *.f90*, *.f95*). Για να
μεταγλωττίσουμε το κώδικα μας τρέχουμε σε ένα τερματικό:

[source,shell]
$ gfortran -o hello hello.f # μετάφραση και μεταγλώττιση του κώδικα.
                            # παράγει το εκτελέσιμο αρχείο "hello"
$ ./hello                   # εκτέλεση του αρχείου
> Hello, World!
