Βασικά στοιχεία
^^^^^^^^^^^^^^^

Το C shell (csh ή πιο πρόσφατα http://www.tcsh.org/Welcome[tcsh]) είναι ένα
κέλυφος (shell) Unix, δηλαδή ένας διερμηνευτής γραμμής εντολών για συστήματα
τύπου Unix.

Το C shell εκτελεί εντολές συνήθως από ένα παράθυρο κειμένου αλλά μπορεί
και να εκτελέσει εντολές αποθηκευμένες σε ένα αρχείο.

Η έκδοση csh που χρησιμοποιούν οι περισσότεροι σύγχρονοι υπολογιστές είναι
το tcsh, μία βελτιωμένη έκδοση του csh. Το tcsh είναι συμβατό με το csh.

Ο στόχος του csh έναντι άλλων κελυφών Unix είναι ότι σχεδιάστηκε με σκοπό
να μοιάζει στη γλώσσα προγραμματισμού C και να είναι καλύτερο για διαδραστική
χρήση.

Τα βασικά εργαλεία που χρειαζόμαστε για να εργαστούμε με το C shell σε μια
διανομή Linux είναι τα παρακάτω:

 * Το tcsh για διερμηνεία των εντολών
 * Επεξεργαστής κειμένου αν θέλουμε να δημιουργήσουμε αρχεία εντολών

Ως επεξεργαστή κειμένου μπορούμε να χρησιμοποιήσουμε οποιονδήποτε προτιμάμε, πχ
vim, nano, gedit, κλπ. Για κονσόλα επίσης κάνει οποιαδήποτε, πχ gnome-terminal,
kterm, xterm, κλπ.

Διερμηνεία Γραμμής Εντολών
^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,tcsh]
% echo Hello, World!
> Hello, World!

Συγγραφή Προγραμμάτων
^^^^^^^^^^^^^^^^^^^^^

[source,tsch]
---------------------------------------------------------------------
#!/usr/bin/env tcsh

echo Hello, World!
---------------------------------------------------------------------

Αφού γράψουμε το κώδικα μας, αποθηκεύουμε το αρχείο με κατάληξη *.csh* ή *.tcsh*.
Για να εκτελέσουμε το κώδικα μας τρέχουμε σε ένα τερματικό:

[source,shell]
$ tcsh hello.csh            # εκτέλεση του αρχείου
> Hello, World!

