Βασικά στοιχεία
^^^^^^^^^^^^^^^

Η HTML (HyperText Markup Language - Γλώσσα Σήμανσης Υπερκειμένου) είναι
η κυρίαρχη *γλώσσα σήμανσης* για τη δημιουργία ιστοσελίδων και τα στοιχεία
της είναι τα βασικά δομικά στοιχεία αυτών.

Οι WebBrowsers διαβάζουν τα αρχεία HTML και αποτυπώνουν την ερμηνεία τους.
Δηλαδή ένας WebBrowser δε θα δείξει το κώδικα HTML της σελίδας αλλά θα
δείξει αυτό που αυτός περιγράφει, δηλαδή μορφοποιημένο κείμενο και πολυμεσικό
περιεχόμενο όπως εικόνες, βίντεο κλπ.

Για να συντάξει κάποιος ένα αρχείο HTML σε μια διανομή Linux χρειάζεται
τα παρακάτω:

 * Επεξεργαστής κειμένου
 * WebBrowser

Ως επεξεργαστή κειμένου μπορούμε να χρησιμοποιήσουμε οποιονδήποτε προτιμάμε, πχ
vim, nano, gedit, κλπ. Για κονσόλα επίσης κάνει οποιαδήποτε, πχ gnome-terminal,
kterm, xterm, κλπ.

Για WebBrowser μπορούμε να χρησιμοποιήσουμε οποιονδήποτε μοντέρνο WebBrowser
που υποστηρίζει τα πιο σύγχρονα πρότυπα (HTML5, CSS3) όπως Firefox, Chromium κλπ.

Συγγραφή Προγραμμάτων
^^^^^^^^^^^^^^^^^^^^^

[source,html]
---------------------------------------------------------------------
<html>
  <head>
    <title>Hello World</title>
  </head>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
---------------------------------------------------------------------

Αφού γράψουμε το κώδικά μας, αποθηκεύουμε το αρχείο με κατάληξη *.html*.
Για να δούμε πώς φαίνεται το ανοίγουμε με κάποιον WebBrowser.

Από γραμμή εντολών μπορούμε να το ανοίξουμε έτσι:

[source,shell]
$ $BROWSER hello.html      # άνοιγμα της σελίδας με τον προεπιλεγμένο browser μας

